import "./globals.css";

export const metadata = {
  title: "Portfolio - Akash",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full antialiased scroll-smooth">
      <body className="min-h-full flex flex-col leading-8 overflow-x-hidden dark:bg-darkTheme dark:text-white">{children}</body>
    </html>
  );
}
